name: 'Retart Docker Containers'
description: 'Restarting docker containers if their files changed'
author: 'Ryno Marree'

# Define your inputs here.
inputs:
  container-names:
    description: 'Names of the docker containers to restart'
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    CONTAINER_NAMES: ${{ inputs.container-names }}
